### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by robertsLando** [miromannino/Contributions-Importer-For-Github#2]
When I run the script I got an error, here the full log output: 

```
Starting

Analysing commit at 2018-12-04 13:04:38
    Commit changes: insertions: {'.md': 3} deletions: {}
    Apply changes: insertions: {'.md': 1} deletions: {}
    Commit at: 2018-12-04 13:04:38

Analysing commit at 2018-12-04 17:16:54
    Commit changes: insertions: {'': 100, '.ejs': 100, '.map': 2, '.json': 100, '.css': 86, '.js': 100} deletions: {}
    Apply changes: insertions: {'': 1, '.ejs': 1, '.map': 1, '.json': 1, '.css': 1, '.js': 1} deletions: {}
Traceback (most recent call last):
  File "import.py", line 21, in <module>
    importer.import_repository()
  File "/Contributions-Importer-For-Github/git_contributions_importer/Importer.py", line 98, in import_repository
    apply(self.content, broken_stats)
  File "/Contributions-Importer-For-Github/git_contributions_importer/generators/__init__.py", line 45, in apply
    gen.insert(content.get(ext), num)
  File "/Contributions-Importer-For-Github/git_contributions_importer/generators/JsonGenerator.py", line 17, in insert
    content.clear()
AttributeError: 'list' object has no attribute 'clear'
```

**Comment by robertsLando** [comment]
Was running command using python instead of python3
